/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksIndexImport } from './routes/tasks/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as TasksCreateIndexImport } from './routes/tasks/create/index'
import { Route as TasksEditIdImport } from './routes/tasks/edit/$id'

// Create/Update Routes

const TasksIndexRoute = TasksIndexImport.update({
  path: '/tasks/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const TasksCreateIndexRoute = TasksCreateIndexImport.update({
  path: '/tasks/create/',
  getParentRoute: () => rootRoute,
} as any)

const TasksEditIdRoute = TasksEditIdImport.update({
  path: '/tasks/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexImport
      parentRoute: typeof rootRoute
    }
    '/tasks/edit/$id': {
      id: '/tasks/edit/$id'
      path: '/tasks/edit/$id'
      fullPath: '/tasks/edit/$id'
      preLoaderRoute: typeof TasksEditIdImport
      parentRoute: typeof rootRoute
    }
    '/tasks/create/': {
      id: '/tasks/create/'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LoginIndexRoute,
  TasksIndexRoute,
  TasksEditIdRoute,
  TasksCreateIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login/",
        "/tasks/",
        "/tasks/edit/$id",
        "/tasks/create/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/tasks/": {
      "filePath": "tasks/index.tsx"
    },
    "/tasks/edit/$id": {
      "filePath": "tasks/edit/$id.tsx"
    },
    "/tasks/create/": {
      "filePath": "tasks/create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
